### PR TITLE
fix: colorful-winsep is on top of lualine #57

### PR DESCRIPTION
**Pull request by liubianshi**
Setting laststatus=3 might reproduce the problem

### CODE REVIEW

**Comment by denstiny** [comment]
@liubianshi  Do you have any interest in helping to maintain this project?

**Comment by liubianshi** [comment]
I'm a complete amateur in programming, so I shouldn't be able to help much.

**Comment by denstiny** [comment]
> I'm a complete amateur in programming, so I shouldn't be able to help much.

Well, check out my fix for your pull

**Review by liubianshi — COMMENTED** [review]
well

**Pull request merged**
