### PR TITLE
fix: error on <C-w>o 

### PR DESCRIPTION
**Pull request by konosubakonoakua**
fix:wrong align on bottom vertical line

### CODE REVIEW

**Comment by denstiny** [comment]
Use api.nvim_win_is_valid whether win = nill is also required

**Comment by konosubakonoakua** [comment]
> Use api.nvim_win_is_valid whether win = nill is also required

IMHO, with `and` expression can fail fast, which avoids useless api calling

**Comment by denstiny** [comment]
> > Use api.nvim_win_is_valid whether win = nill is also required
> 
> IMHO, with `and` expression can fail fast, which avoids useless api calling
IMHO, fix: wrong align on bottom vertical line should create an issue first

**Comment by denstiny** [comment]
I can merge fix for you: error on <C-w>o

**Comment by denstiny** [comment]
2f0823546c872ea8976a36ebfa2502458e93d983  I'd like to see your minimal reproducible code first

**Review by denstiny — APPROVED** [review]

**Comment by konosubakonoakua** [comment]
> [2f08235](https://github.com/nvim-zh/colorful-winsep.nvim/commit/2f0823546c872ea8976a36ebfa2502458e93d983) I'd like to see your minimal reproducible code first

This turns out to be a theme issue, covering the winbar.
I tried with other configs, just work~
I think we can merge the `<C-w>o` fix only.

**Comment by denstiny** [comment]
Could you provide a minimal code to reproduce the issue? I'd like to try reproducing it myself first.

**Comment by konosubakonoakua** [comment]
> Could you provide a minimal code to reproduce the issue? I'd like to try reproducing it myself first.

Okey, I reproduced the issue only with this plug & lazy.nvim
here's the minimal config:
```lua
-- [[ Install `lazy.nvim` plugin manager ]]
--    https://github.com/folke/lazy.nvim
--    `:help lazy.nvim.txt` for more info
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    "nvim-zh/colorful-winsep.nvim",
    config = true,
    event = { "WinNew" },
  }
})
```

**Comment by konosubakonoakua** [comment]
> > Could you provide a minimal code to reproduce the issue? I'd like to try reproducing it myself first.
> 
> Okey, I reproduced the issue only with this plug & lazy.nvim here's the minimal config:
> 
> ```lua
> -- [[ Install `lazy.nvim` plugin manager ]]
> --    https://github.com/folke/lazy.nvim
> --    `:help lazy.nvim.txt` for more info
> local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
> if not vim.loop.fs_stat(lazypath) then
>   vim.fn.system {
>     'git',
>     'clone',
>     '--filter=blob:none',
>     'https://github.com/folke/lazy.nvim.git',
>     '--branch=stable', -- latest stable release
>     lazypath,
>   }
> end
> vim.opt.rtp:prepend(lazypath)
> 
> require('lazy').setup({
>   {
>     "nvim-zh/colorful-winsep.nvim",
>     config = true,
>     event = { "WinNew" },
>   }
> })
> ```

The horizontal line is not aligned with the winbar in up window

**Comment by denstiny** [comment]
There is a lingering issue where the status bar is being covered, and I'm sorry, but I don't have any free time to address it.

**Comment by denstiny** [comment]
You can enable WinBar for now, and I'll fix it when I have the time.

**Pull request closed without merging**
