### PR TITLE
Readme Packer.nvim incorrect syntax

### PR DESCRIPTION
**Pull request by 4542elgh**

### CODE REVIEW

**Review by denstiny — CHANGES_REQUESTED** [review]
thank you

**Review by denstiny — APPROVED** [review]

**Comment by jdhao** [comment]
@4542elgh FYI, the original is perfectly fine because the value for `config` can be either a string or a function. See packer official doc: https://github.com/wbthomason/packer.nvim#specifying-plugins

**Comment by 4542elgh** [comment]
I am aware the original way of writing config attribute is fine and there is nothing wrong about it.
But there were 2 things wrong with `reqire('colorful-winsep.nvim')`
1. `reqire` is spelled wrong
2. when requiring, I normally dont see the `.nvim` extension at the back, and I was getting an error
image
I look over other configs before figuring out I need to drop the `.nvim` and `require('colorful-winsep')` is what made it work.

So at the end I could and should just updated it with `config = [[require('colorful-winsep').setup()]]` so it is consistent with your original format. Nothing against you, the posted format was what worked for me 🙂

**Comment by jdhao** [comment]
thanks, I overlooked the typo and the plugin directory name. I thought the directory name is the same as the plugin names. Thanks for spotting the mistakes 👍

**Pull request merged**
