### PR TITLE
docs: Rewrite help file

### PR DESCRIPTION
**Pull request by 4513ECHO**
First of all, thanks for creating such a great plugin. The plugin always helps me.
Currently colorful-winsep.nvim has a vim help file, but it is too ugly and does not follow the way of vim help file.
I have rewritten the help file to follow the right way. I hope it will help other users when they try to read the document.

### CODE REVIEW

**Review by denstiny — APPROVED** [review]

**Comment by denstiny** [comment]
#44 correct direction_have sample

**Comment by denstiny** [comment]
😭I'm sorry, I don't quite understand the git specification. I didn't mean to. I didn't know it was wrong until I asked my friends. I'm sorry.

**Comment by 4513ECHO** [comment]
Don't mind. Finally the changes have been included to the plugin. That's all I need.

**Comment by denstiny** [comment]
> Don't mind. Finally the changes have been included to the plugin. That's all I need.

😚I like you.

**Pull request merged**
